-- ==========================================
-- 1. ESTRUCTURA DE TABLAS (FORCE COLUMNS)
-- ==========================================

-- Tabla Perfiles
create table if not exists public.perfiles (
  id uuid references auth.users on delete cascade not null primary key,
  nombre text not null,
  rol text not null check (rol in ('super_admin', 'admin', 'recepcion', 'mantenimiento', 'limpieza', 'direccion')),
  hotel text not null default 'Hotel Central',
  permisos text[] default array['dashboard', 'incidencias', 'chat']::text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.perfiles add column if not exists hotel text not null default 'Hotel Central';

-- Tabla Incidencias
create table if not exists public.incidencias (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  priority text not null check (priority in ('low', 'medium', 'high')),
  status text not null default 'pending' check (status in ('pending', 'in-progress', 'resolved')),
  reporter_id uuid references public.perfiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.incidencias add column if not exists hotel text not null default 'Hotel Central';
alter table public.incidencias add column if not exists assigned_to uuid references public.perfiles(id);
alter table public.incidencias add column if not exists descripcion text;
alter table public.incidencias add column if not exists media_urls text[];

-- Tabla Controles 
create table if not exists public.controles (
  id bigint generated by default as identity primary key,
  title text not null,
  area text not null,
  assignee_id uuid references public.perfiles(id) not null,
  status text not null default 'pending' check (status in ('pending', 'in-progress', 'resolved')),
  items integer not null default 5,
  completed integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.controles add column if not exists hotel text not null default 'Hotel Central';

-- Tabla Mensajes de Chat
create table if not exists public.mensajes (
  id bigint generated by default as identity primary key,
  channel text not null,
  text_content text not null,
  sender_id uuid references public.perfiles(id) not null,
  read boolean not null default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.mensajes add column if not exists hotel text not null default 'Hotel Central';

-- Tabla de Zonas
create table if not exists public.zonas (
    id uuid default gen_random_uuid() primary key,
    nombre text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.zonas add column if not exists hotel text not null default 'Hotel Central';

-- Tabla de Inventario
create table if not exists public.inventario (
    id uuid default gen_random_uuid() primary key,
    nombre text not null,
    categoria text not null,
    stock_actual integer default 0,
    stock_minimo integer default 5,
    unidad text default 'unidades',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table public.inventario add column if not exists hotel text not null default 'Hotel Central';

-- ==========================================
-- 2. HABILITAR RLS Y POLÍTICAS (CON ALIAS EXPLÍCITOS)
-- ==========================================

-- Perfiles (MODO EMERGENCIA: Desactivar RLS preventivamente para restaurar acceso)
alter table public.perfiles disable row level security;
drop policy if exists "Usuarios ven su propio perfil" on public.perfiles;
drop policy if exists "Usuarios ven otros de su hotel" on public.perfiles;

-- Incidencias (MODO SIMPLIFICADO: Solo auth para recuperar visibilidad)
alter table public.incidencias disable row level security;
alter table public.mensajes disable row level security;
alter table public.controles disable row level security;
alter table public.zonas disable row level security;
alter table public.habitaciones disable row level security;
alter table public.inventario disable row level security;
alter table public.contadores disable row level security;
alter table public.lecturas disable row level security;

drop policy if exists "Insertar incidencias por hotel" on public.incidencias;
create policy "Insertar incidencias por hotel" on public.incidencias for insert to authenticated 
with check ( hotel = (select p.hotel from public.perfiles p where p.id = auth.uid()) or (select p2.rol from public.perfiles p2 where p2.id = auth.uid()) = 'super_admin' );

-- Mensajes
alter table public.mensajes enable row level security;
drop policy if exists "Mensajes visibles por hotel" on public.mensajes;
create policy "Mensajes visibles por hotel" on public.mensajes for select to authenticated 
using ( hotel = (select p.hotel from public.perfiles p where p.id = auth.uid()) or (select p2.rol from public.perfiles p2 where p2.id = auth.uid()) = 'super_admin' );

-- ==========================================
-- 3. FUNCIONES Y TRIGGERS
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.perfiles (id, nombre, rol, hotel, permisos)
  values (
    new.id, 
    coalesce(new.raw_user_meta_data->>'nombre', 'Nuevo Usuario'), 
    coalesce(new.raw_user_meta_data->>'rol', 'recepcion'), 
    coalesce(new.raw_user_meta_data->>'hotel', 'Hotel Central'),
    coalesce(
      (new.raw_user_meta_data->'permisos')::text[], 
      array['dashboard', 'incidencias', 'chat']::text[]
    )
  );
  return new;
end;
$$ language plpgsql security definer;
